site_name: DL Server Wiki
nav:
  - Home: ./README.md
  - ssh: ssh/README.md
  - GitHub: github/README.md
  - Linux: linux/README.md
  - Conda: conda/README.md
  - GPU: gpu/README.md
  - grafana: grafana/README.md
  - misc: misc/README.md

theme:
  name: material